### ISSUE TITLE
Missing htpasswd and cannot make use of authentication

### ISSUE THREAD

**Issue by lazarus477** [koue/httpd#3]
Hello.

On **FreeBSD 10.3-RELEASE** I am missing **htpasswd** for managing user **credentials** for **obhttpd**. My workaround has been to use an online **bcrypt** tool to generate bcrypt encoded passwords and then manually adding these to a hand written file containing username:password (bcrypt).

Have also tried using Apache htpasswd -B, but the bcrypt format/version appears to be incompatible with obhttpd.

**Comment by koue** [comment]
[https://github.com/koue/httpd/commit/031687d1049ca141b95db24b9afeb0edc5646f78](https://github.com/koue/httpd/commit/031687d1049ca141b95db24b9afeb0edc5646f78)
htpasswd has been added. It will appear in the next release version. For now you can clone the code and build it by your own.
