### ISSUE TITLE
getdtablecount

### ISSUE THREAD

**Issue by ghost** [koue/httpd#5]
I think the `getdtablecount` implementation could be a lot simpler (and faster) on FreeBSD >= 11.0 by simply looking up the `kern.proc.nfds` sysctl.

For reference there is a getdtablecount implementation in the FreeBSD src tree: https://github.com/freebsd/freebsd/blob/master/lib/libopenbsd/getdtablecount.c

**Comment by koue** [comment]
getdtablecount implementation from the FreeBSD src tree has been applied. Thanks.
