### ISSUE TITLE
Still "server_tls_init: failed to initialise tls" problem on FREEBSD 13.0_RELEASE ports&pkg

### ISSUE THREAD

**Issue by tzauner** [koue/httpd#6]
Evening,

I just tried to use obhttpd on13.0-RELEASRE from ports an packages and ran into a 
"server_tls_init: failed to initialise tls"
problem.

I found the discussion on:
https://forums.freebsd.org/threads/use-obhttpd-with-tls.71960/
and your patch at:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249894

I was not able to apply the patch on the current port snapshot. 
Ports tree, packages  and port-git still are on version 6.6.20191023
Is there a way to get the fixed version 6.7.20200925 into ports/pkg.

Thx for you time and work!
I really would love to get obhhtp with TLS running on the 13.0 RELEASE

Best Regards
Thomas

**Comment by koue** [comment]
Hey, Thomas,

Yes, you're right, the patch is old and it has to be updated. I'll prepare new one.

Thanks for reporting,
Nikola

**Comment by tzauner** [comment]
Hi Nikola,

did you find the time to update the patch. 
If you are a little short with free time. I will check out your git and start a little tinkering myself. :-)
Mybee I can get it to work just for my server locally.


Best regards,
Thomas

**Comment by koue** [comment]
Hey Thomas,

I'll have time at the end of the week. Of course you're free to try it yourself.

Regards,
Nikola

**Comment by koue** [comment]
Hi Thomas,

Please check https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249894 for update.

Regards,
Nikola
